services:
  - type: web
    name: pearls-aqi-predictor1
    runtime: python
    buildCommand: pip install -r app/requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
